### ISSUE TITLE
Suggestion: Make the yml files actually human readable

### ISSUE THREAD

**Issue by Andre601** [erikzimmermann/WarpSystem-IssueTracker#238]
I suggest to change the formats of the files, where stuff is stored, to make it more human readable, as it is really difficult to see and find stuff...

For example:
This is a entry of a custom player head for a folder in the WarpGU (Saved in ActionItems.yml)
```yaml
Icons:
- '{"item":"{\"Type\":\"PLAYER_HEAD\",\"Lore\":[\"§f§7Contains warps, that\",\"§f§7are free to use.\"],\"SkullOwner\":\"4312ca4632def5ffaf2eb0d9d7cc7b55a50c4e3920d90372aab140781f5dfbc4\",\"Amount\":1,\"Durability\":3,\"Data\":3,\"Name\":\"&r&aFree\"}","name":"&aFree","slot":20,"isPage":true}'
```

This is barely readable and having it as JSON doesn't really make that much sense for me...
So instead have it like that:
```yaml
Icons:
  '&aFree': # Save it through the provided name? Or maybe the slot?
    Type: PLAYER_HEAD
    Amount: 1
    Durability: 3
    Data: 3
    Name: '&r&aFree'
    SkullOwner: '4312ca4632def5ffaf2eb0d9d7cc7b55a50c4e3920d90372aab140781f5dfbc4'
    Lore:
    - '§f§7Contains warps, that'
    - '§f§7are free to use.'
```

If you retrieve the information for the items as JSON, then maybe have some sort of JSON to yaml converter?
In that case would perhaps Gson be a good option to get the JSON, parse it to different values within a class and then save those values in the yaml as specific paths...

This is just an idea.
