### ISSUE TITLE
[RTP] Unsafe teleportations

### ISSUE THREAD

**Issue by erikzimmermann** [erikzimmermann/WarpSystem-IssueTracker#691]
**Describe the bug**
What can I do to stop players from ending up on the Nether roof with random teleports?
Our teleport goes Spawn world -> RTP to Nether
If I understand correctly, our config should already prevent any teleportation to the Nether roof?
I've also set the Nether roof to be a no-entry zone with WorldGuard, but that has not helped with RTP either.

```
RTP Config:
  Range:
    Highest_Y:
      Nether: 120

    - RulerSpawn_nether:
        startX: 0
        startY: 70
        startZ: 0

  Block_Blacklist:
    Enabled: true
    List:
    - Water
    - Lava
    - Bedrock
    - Fire
```
Could a 'double RTP' cause this kind of issues? Sometimes players get RTP'd twice.
Had a player die again in Nether roof and he didnt get double RTP'd so I dont think its that.

**Discord contact**: Graddod#9153
