### ISSUE TITLE
Paper 1.19.4 to 1.20.4 upgrade breaks ActionIcons

### ISSUE THREAD

**Issue by terbin** [erikzimmermann/WarpSystem-IssueTracker#769]
**Describe the bug**
Updating my server from 1.19.4 to 1.20.4 using WarpSystem_v5.1.9_Hotfix-2 breaks several ActionIcons. 150 of mine to be precise.
Here is an example:

**Paper 1.19.4**
```
- item:
    Type: GRASS
    Amount: 1
    HideStandardLore: true
    Name: Spawn 2011-11-16
  name: Spawn 2011-11-16
  slot: 9
  page: Overworld Spawn
  performed: 9538
  actions:
  - value:
      destination:
        id: Spawn_2011-11-16
        type: 1
```

**After update to Paper 1.20.4**
```
- name: Spawn 2011-11-16
  slot: 9
  page: Overworld Spawn
  performed: 9538
  actions:
  - value:
      destination:
        id: Spawn_2011-11-16
        type: 1
```

**To Reproduce**
Update paper server from 1.19.4 to 1.20.4

**Expected behavior**
ActionIcons stay the same after a 1.19.4 to 1.20.4 upgrade.
